name: Convert YAML to tfvars
on:
  push:
    branches: [ main ]
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yq for YAML processing (optional)
        run: sudo apt-get update && sudo apt-get install -y yq  # Only necessary if you prefer yq over native YAML parsing
      - name: Convert YAML to tfvars (using native YAML parsing)
        run: |
          cat variables.yaml | jq -r '. as entries | to_entries | map(.key + " = " + .value) | .[]' > terraform.tfvars
      - name: Convert YAML to tfvars (using yq - optional)
        run: |  # Uncomment if using yq
          yq -r '. as entries | to_entries[] | (.key + "=" + .value) | .[]' variables.yaml > terraform.tfvars
      - name: Verify tfvars content (optional)
        run: cat terraform.tfvars
