name: Convert YAML to TFVar and Deploy GCP Resources

on:
  push:
    paths:
      - 'input.yaml'

jobs:
  convert_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyhcl
        
    - name: Convert YAML to HCL
      run: |
        python convert_yaml_to_hcl.py
        
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add terraform.tfvars
        git commit -m "Convert YAML to HCL"
        git push
