name: Convert Values to tfvars
on:
  push:
    branches:
      - main  # Adjust this according to your repository's default branch
jobs:
  convert_values:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need
    - name: Install PyYAML
      run: pip install pyyaml
    - name: Convert values.yaml to tfvars
      run: python convert.py values.yaml values.tfvars  # Adjust this according to your actual conversion script
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@users.noreply.github.com"
        git add values.tfvars
        git commit -m "Convert values.yaml to tfvars"
        git push
