name: Deploy GCP Resources
on:
  pull_request:
    types: [opened]

jobs:
  deploy_gcp_resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Read values from YAML
        id: read_yaml
        run: |
          echo "::set-output name=project_id::$(cat variables.yaml | yq -r .project_id)"
          echo "::set-output name=region::$(cat variables.yaml | yq -r .region)"
          echo "::set-output name=zone::$(cat variables.yaml | yq -r .zone)"
          echo "::set-output name=machine_type::$(cat variables.yaml | yq -r .machine_type)"
          echo "::set-output name=image::$(cat variables.yaml | yq -r .image)"

      - name: Generate tfvars
        run: |
          echo "project_id = \"$PROJECT_ID\"" > terraform-variables.tfvars
          echo "region = \"$REGION\"" >> terraform-variables.tfvars
          echo "zone = \"$ZONE\"" >> terraform-variables.tfvars
          echo "machine_type = \"$MACHINE_TYPE\"" >> terraform-variables.tfvars
          echo "image = \"$IMAGE\"" >> terraform-variables.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Commit tfvars changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add terraform-variables.tfvars
          git commit -m "Update tfvars"
          git push
